### ISSUE TITLE
Cannot assign custom components with MDXProvider

### ISSUE THREAD

**Issue by Hayao0819** [Hayao0819/hayao0819.com#3]
I want to set `H2` components as `##` in markdown.

I tried to use MDXProvider and committed in 2442029a1da251cb18f1c572d806a27540f78858

Run `pnpm run dev` and go to `localhost:3000/test` the I can get and [the error](https://nextjs.org/docs/messages/react-hydration-error) on the console.

I have no idea to fix it.

**Comment by orzklv** [comment]
Done :D https://github.com/Hayao0819/hayao0819.com/commit/cb1d2857a8685abbbdf49b0b05bd27be1d3e2c52
