### ISSUE TITLE
Redirect /blog to another domain

### ISSUE THREAD

**Issue by Hayao0819** [Hayao0819/hayao0819.com#4]
Redirect `https://www.hayao0819.com/blog/hogehoge` to `https://old.hayao0819.com/blog/`

**Comment by orzklv** [comment]
you sure about that? XD

**Comment by orzklv** [comment]
done blyat. https://github.com/Hayao0819/hayao0819.com/commit/bd509de42704a45ac2658e99ec0c38f06f0cea79
