### ISSUE TITLE
Blog system is broken on vercel deploy

### ISSUE THREAD

**Issue by Hayao0819** [Hayao0819/hayao0819.com#8]
Blog will work on local but not on vercel.

[https://website-kz83g3xde-hayao0819.vercel.app/diary/posts/20230721/hello-world](https://website-kz83g3xde-hayao0819.vercel.app/diary/posts/20230721/hello-world)

**Comment by orzklv** [comment]
emmm... apparently, it's working!
![image](https://github.com/Hayao0819/hayao0819.com/assets/54666588/9e32a35a-5562-4a20-b0c0-cc8c80504be9)

**Comment by Hayao0819** [comment]
Categoris and pages works correctly but each link of articles are 404 on only vercel

**Comment by Hayao0819** [comment]
You can check it.

Local: http://localhost:3000/diary/posts/20230721/hello-world
Vercel: https://www-dev.hayao0819.com/diary/posts/20230721/hello-world

**Comment by Hayao0819** [comment]
The first  merging commit about blog with markdown has also the same issue.

[https://website-3epg54aq0-hayao0819.vercel.app/diary](https://website-3epg54aq0-hayao0819.vercel.app/diary)

**Comment by Hayao0819** [comment]
It seems that output does not have diaries markdown?
<img width="1292" alt="image" src="https://github.com/Hayao0819/hayao0819.com/assets/32128205/06e5d261-7f9d-4cc8-bc6d-92323d0d1e2d">

**Comment by Hayao0819** [comment]
<img width="1305" alt="image" src="https://github.com/Hayao0819/hayao0819.com/assets/32128205/67181a69-f332-4d81-93c7-433227ff01f4">

**Comment by Hayao0819** [comment]
I have found the solution in 9b8e1475a69e68a0cd93e05709582b60ef053f37
